orbs:
  react: thefrontside/react@0.1.0
version: 2.1
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          type: approval
          requires:
            - react/install
      - react/test:
          type: approval  
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install